"""Fourth Migration

Revision ID: 218e87dc7bf1
Revises: e7385db5b53f
Create Date: 2024-04-29 05:32:45.298569

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '218e87dc7bf1'
down_revision: Union[str, None] = 'e7385db5b53f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('resumption_time', sa.Time(), nullable=True))
    op.add_column('users', sa.Column('closing_time', sa.Time(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'closing_time')
    op.drop_column('users', 'resumption_time')
    # ### end Alembic commands ###
