"""Fourth Migration

Revision ID: e7385db5b53f
Revises: cc1f3d535c48
Create Date: 2024-04-28 21:26:50.934478

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e7385db5b53f'
down_revision: Union[str, None] = 'cc1f3d535c48'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_message_recipients_id', table_name='message_recipients')
    op.drop_table('message_recipients')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('message_recipients',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('message_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('recipient_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], name='message_recipients_message_id_fkey'),
    sa.ForeignKeyConstraint(['recipient_id'], ['users.id'], name='message_recipients_recipient_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='message_recipients_pkey')
    )
    op.create_index('ix_message_recipients_id', 'message_recipients', ['id'], unique=False)
    # ### end Alembic commands ###
